#ifndef DE_UNISTUTTGART_ISTE_SQA_MPW_KARASIMULATOR_CPP_UIDIMENSIONS_H
#define DE_UNISTUTTGART_ISTE_SQA_MPW_KARASIMULATOR_CPP_UIDIMENSIONS_H

namespace karasimulator {

const int MIN_WINDOW_WIDTH = 660;
const int MIN_WINDOW_HEIGHT = 300;

const int TOOLBAR_MARGIN = 8;
const int WORLD_GAMELOG_MARGIN = 10;
const int BUTTON_SIZE = 48;
const int WORLD_OFFSET = 80;
const int MINIMUM_TILE_SIZE = 20;
const int GAMELOG_MIN_WIDTH = 200;
const int SLIDER_X = 250;
const int SLIDER_WIDTH = 160;
const int SLIDER_HEIGHT = 20;

}

#endif //DE_UNISTUTTGART_ISTE_SQA_MPW_KARASIMULATOR_CPP_UIDIMENSIONS_H
